name: Deploy Service
on: 
  workflow_call:
    inputs:
      service:
        required: true
        type: string
      account:
        required: true
        type: string
      commit_hash:
        required: true
        type: string
      sonar_scan_path:
        type: string
      api_test_env_vars:
        required: true
        type: string
      database_migration_dockerfile:
        type: string
      dotnet_sonar_scan:
        type: boolean
    secrets:
      aws_key:
        required: true
      aws_secret:
        required: true
      region:
        required: true
      sonar_token:
      api_test_secret_vars:
      

env: 
  AWS_ACCESS_KEY_ID: ${{ secrets.aws_key }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret }}
  AWS_DEFAULT_REGION: ${{ secrets.region }}
  DEPLOY_SERVICE: ${{ inputs.service }}
  DEPLOY_ACCOUNT: ${{ inputs.account }}
  API_TEST_ENV_VARS: ${{ inputs.api_test_env_vars }}
  API_TEST_SECRET_VARS: ${{ secrets.api_test_secret_vars }}
  SONAR_SCAN_PATH: ${{ inputs.sonar_scan_path }}
  SONAR_TOKEN: ${{ secrets.sonar_token }}
  DATBASE_MIGRATION_DOCKERFILE: ${{ inputs.database_migration_dockerfile }}
  TF_VAR_commit_sha: ${{ inputs.commit_hash }}
jobs:
  deploy-service:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: recipopdev/github-workflows
          path: github-workflows

      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.4
          terraform_wrapper: false

      - name: Copy deployment scripts
        id: deployment-scripts
        run: cp github-workflows/scripts/linux/*.sh deploy/

      - name: Fetch & iterate version
        id: iterate-version
        run: |
          bash versioning.sh get_service_version $DEPLOY_SERVICE
          if [[ $DEPLOY_ACCOUNT == "uat" ]]; then
            npm version patch
          fi
          if [[ $DEPLOY_ACCOUNT == "production" ]]; then
            npm version minor
          fi
        working-directory: deploy/

      - name: Install dependencies
        id: dependencies
        run: pip3 install --user Jinja2 PyYAML boto3
        working-directory: deploy/

      - name: Generate ECR token
        id: token
        run: bash authenticate.sh $(echo "."$DEPLOY_ACCOUNT"_account")
        working-directory: deploy/

      - name: Bootstrap terraform files
        id: bootstrap
        run: python3 bootstrap.py;
        working-directory: deploy/

      - name: Prepare deployment files
        id: prepare
        run: |
          cp ./deploy/*.tf* .
          cp ./deploy/package.json .

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check -diff

      - name: Terraform Init
        id: init
        run: terraform init -input=false

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Select Workspace
        id: workspace
        run: |
          if [[ $DEPLOY_ACCOUNT == "uat" ]]; then
            terraform workspace select uat
          fi
          if [[ $DEPLOY_ACCOUNT == "production" ]]; then
            terraform workspace select prod
          fi

      - name: Run Database Migration
        if: ${{ inputs.database_migration_dockerfile != '' }}
        id: database-migration
        run: |
          source deploy/switch_role.sh $(echo "."$DEPLOY_ACCOUNT"_account")
          docker build --build-arg AWS_REGION=$AWS_DEFAULT_REGION --build-arg AWS_ACCESS_KEY_ID=$SWITCHED_AWS_ACCESS_KEY_ID --build-arg AWS_SECRET_ACCESS_KEY=$SWITCHED_AWS_SECRET_ACCESS_KEY --build-arg AWS_SESSION_TOKEN=$SWITCHED_AWS_SESSION_TOKEN -f $DATABASE_MIGRATION_DOCKERFILE .

      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve -input=false

      - name: Terraform Confirm
        id: confirm
        run: terraform plan -input=false -detailed-exitcode

      - name: Scan Docker Image
        id: image-scan
        run: bash image_scan.sh $(echo "."$DEPLOY_ACCOUNT"_account") $DEPLOY_SERVICE
        working-directory: deploy/

      - name: Run Sonar Scanner
        if: ${{ inputs.sonar_scan_path != '' }}
        id: sonar-scan
        run: docker run -e SONAR_HOST_URL="https://sonarqube.mgmt.newadimo.co" -e SONAR_LOGIN=$SONAR_TOKEN -v "$(pwd)/"$SONAR_SCAN_PATH":/usr/src" sonarsource/sonar-scanner-cli -Dsonar.projectKey=$DEPLOY_SERVICE

      - name: Run DotNet Sonar Scanner
        if: ${{ inputs.dotnet_sonar_scan }}
        id: dotnet-sonar-scan
        uses: calxus/action-sonarqube-dotnet@1.0.0
        with:
          sonarProjectKey: $DEPLOY_SERVICE
          sonarHostname: "https://sonarqube.mgmt.newadimo.co"

      - name: Track deployment rollout
        id: track-rollout
        run: bash track_deployment.sh $(echo "."$DEPLOY_ACCOUNT"_account") $DEPLOY_SERVICE
        working-directory: deploy/

      - name: Combining API Test Environment Variables
        id: combine-api-vars
        run: |
          if [[ $API_TEST_SECRET_VARS != "" ]]; then
            API_TEST_VARS=$(echo -e "$API_TEST_ENV_VARS\n$API_TEST_SECRET_VARS" | jq -s 'add' --raw-output)
          else
            API_TEST_VARS=$(echo -e "$API_TEST_ENV_VARS")
          fi
          echo "::set-output name=api-test-vars::$(echo $API_TEST_VARS)"

      - name: Run API Tests
        id: run-tests
        uses: matt-ball/newman-action@master
        with:
          collection: deploy/tests/tests.json
          envVar: ${{ steps.combine-api-vars.outputs.api-test-vars }}

      - name: Commit version
        id: commit-version
        run: |
          if [[ $DEPLOY_ACCOUNT != "development" ]]; then
            bash versioning.sh set_service_version $DEPLOY_SERVICE
          fi
        working-directory: deploy/
